variables:
  projectName: ToolsToLive.AuthCore
  version: 3.0.0

stages:
  - build
  - pack
  - publish

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet publish $projectName/$projectName.csproj -c Release /p:Version=$version.$CI_PIPELINE_IID -r win-x64 -o $projectName/bin/Release/publish

  artifacts:
    expire_in: 1h
    name: "$projectName.$CI_PIPELINE_ID"
    paths:
      - $projectName/bin/Release/publish

.pack_definition:
  stage: pack
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet pack -c Release /p:Version=$Ver
  artifacts:
    expire_in: 1h
    name: "$projectName.$CI_PIPELINE_ID"
    paths:
      - $projectName/bin/Release/$projectName.$Ver.nupkg

pack_master:
  extends: .pack_definition
  variables:
    Ver: $version
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

pack_alpha:
  extends: .pack_definition
  variables:
    Ver: $version-alpha.$CI_PIPELINE_IID
  rules:
    - if: '$CI_COMMIT_BRANCH == "alpha"'
      when: on_success

# publish (send to nuget)
.publish_definition:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet nuget push $projectName/bin/Release/$projectName.$Ver.nupkg --source https://api.nuget.org/v3/index.json --api-key $nugetpush

publish_master:
  extends: .publish_definition
  dependencies:
    - pack_master
  variables:
    Ver: $version
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  
publish_alpha:
  extends: .publish_definition
  dependencies:
    - pack_alpha
  variables:
    Ver: $version-alpha.$CI_PIPELINE_IID
  rules:
    - if: '$CI_COMMIT_BRANCH == "alpha"'
      when: on_success
