variables:
  version: 3.0.0

stages:
  - build
  - publish

# build nuget
.build_nuget_definition:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet pack backend/ToolsToLive.AuthCore/ToolsToLive.AuthCore.csproj -c Release /p:Version=$Ver
  artifacts:
    expire_in: 1h
    name: "ToolsToLive.AuthCore.$CI_PIPELINE_ID"
    paths:
      - backend/ToolsToLive.AuthCore/bin/Release/ToolsToLive.AuthCore.$Ver.nupkg

build_nuget_master:
  extends: .build_nuget_definition
  variables:
    Ver: $version
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

build_nuget_alpha:
  extends: .build_nuget_definition
  variables:
    Ver: $version-alpha.$CI_PIPELINE_IID
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: on_success

# build npm
build_npm:
  stage: build
  image: node:14.15-alpine
  script:
    - cd frontend/auth-core
    - npm ci
    - npm run lib:build
  artifacts:
    expire_in: 1h
    name: auth-core.$CI_PIPELINE_ID"
    paths:
      - frontend/auth-core/dist/auth-core
    when: on_success


# publish nuget package
.publish_nuget_definition:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet nuget push backend/ToolsToLive.AuthCore/bin/Release/ToolsToLive.AuthCore.$Ver.nupkg --source https://api.nuget.org/v3/index.json --api-key $nugetpush

publish_nuget_master:
  extends: .publish_nuget_definition
  dependencies:
    - build_nuget_master
  variables:
    Ver: $version
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  
publish_nuget_alpha:
  extends: .publish_nuget_definition
  dependencies:
    - build_nuget_alpha
  variables:
    Ver: $version-alpha.$CI_PIPELINE_IID
  rules:
    - if: '$CI_COMMIT_BRANCH != "alpha"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "alpha"'
      when: manual

# publish npm package
publish_npm:
  stage: publish
  image: node:14.15-alpine
  dependencies:
    - build_npm
  script:
    - npm config set //registry.npmjs.org/:_authToken ${npmpublish}
    - cd frontend/auth-core
    - npm publish dist/auth-core --access public
  rules:
    - if: '$CI_COMMIT_BRANCH != "alpha"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "alpha"'
      when: manual
