variables:
  version: 3.0.0

stages:
  - build
  - publish

  # build nuget
.build-back_definition:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet pack -c Release /p:Version=$Ver -r win-x64
  artifacts:
    expire_in: 1h
    name: "ToolsToLive.AuthCore.$CI_PIPELINE_ID"
    paths:
      - backend/ToolsToLive.AuthCore/bin/Release/ToolsToLive.AuthCore.$Ver.nupkg

build-back_master:
  extends: .build-back_definition
  variables:
    Ver: $version
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

build-back_alpha:
  extends: .build-back_definition
  variables:
    Ver: $version-alpha.$CI_PIPELINE_IID
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: on_success

  # build npm
build-front:
  stage: build
  image: node:14.15-alpine
  script:
    - cd frontend/auth-core
    - npm ci
    - npm run lib:build
  artifacts:
    expire_in: 1h
    name: auth-core.$CI_PIPELINE_ID"
    paths:
      - frontendauth-core/dist/auth-core
    when: on_success


# publish nuget package
.publish-back_definition:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet nuget push backend/ToolsToLive.AuthCore/bin/Release/ToolsToLive.AuthCore.$Ver.nupkg --source https://api.nuget.org/v3/index.json --api-key $nugetpush
  rules:
    - if: '$CI_COMMIT_BRANCH != "alpha" && $CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "alpha" || $CI_COMMIT_BRANCH == "master"'
      when: manual

publish-back_master:
  extends: .publish-back_definition
  dependencies:
    - build-back_master
  variables:
    Ver: $version
  
publish-back_alpha:
  extends: .publish-back_definition
  dependencies:
    - build-back_alpha
  variables:
    Ver: $version-alpha.$CI_PIPELINE_IID

# publish npm package
.publish-front:
  stage: publish
  image: node:14.15-alpine
  dependencies:
    - build-front
  script:
    - npm config set //registry.npmjs.org/:_authToken ${npmpublish}
    - cd frontend/auth-core
    - npm publish dist/auth-core --access public
  rules:
    - if: '$CI_COMMIT_BRANCH != "alpha" && $CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "alpha" || $CI_COMMIT_BRANCH == "master"'
      when: manual
